### ISSUE TITLE
when I use this project，I find the utt2spk and spk2utt files is not seem as the kaldi need,and get a false

### ISSUE THREAD

**Issue by renzeyu-ai** [monkeyboot/Common-Voice-Kaldi#1]
utils/validate_data_dir.sh: spk2utt and utt2spk do not seem to match

how can i do to deal with it?thanks

**Comment by monkeyboot** [comment]
is the number of lines between spk2utt and utt2spk the same length?
and is the last line just a newline with no id?
if yes, try delete newline in the last line in spk2utt and utt2spk

**Comment by renzeyu-ai** [comment]
thanks，I get the answer. When I detect the content of spk2utt and utt2spk , I found them disordered. After sorting the audio sequence number, the problem is solved.
